### ISSUE TITLE
Clothier - Doesn't seem to differentiate between light and medium armor

### ISSUE THREAD

**Issue by Coros** [kierdavis/NoResearchDupes#2]
I have several items marked as dupes that are the only item of that type and trait.  I believe the addon may be ignoring light vs medium and treating them as the same.  This doesn't seem to be an issue with blacksmithing.

**Comment by kierdavis** [comment]
Thanks for the report!

I don't know what could be causing this, off the top of my head. I'll take
a look at the code tomorrow but in the meantime could you send some
screenshots of the issue? I suspect it might be due to the particular items
involved. E.g. another add-on I maintain had a bug where Helmets would be
incorrectly processed as if they were Helms due to the similarity in name.

**Comment by kierdavis** [comment]
Also, do you know if this problem was resolved by itself after reloading
the UI?

I know there's a super subtle bug where NoResearchDupes's internal database
gets out of sync with the real inventory database and starts marking the
wrong items as dupes, but it's been really hard to reproduce this behaviour
- I was just going to completely rewrite the core code in a different way
instead.

**Comment by Coros** [comment]
I’ll check tomorrow. Thanks for the quick responses.

**Comment by Coros** [comment]
I was unable to reproduce the issue today.  If I see it again, I'll reload the UI...if I still see it.  I'll gather screenshots for you.
